// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCswreasBS-d_h8dQn4_3FHnOivYMtDLEU',
    appId: '1:919591073641:web:9731730173d8b8c64caff8',
    messagingSenderId: '919591073641',
    projectId: 'healthvault-6af37',
    authDomain: 'healthvault-6af37.firebaseapp.com',
    storageBucket: 'healthvault-6af37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLDuGgC7ln2i37FDt6-Zgiv9KrH3_Syg',
    appId: '1:919591073641:android:6bbfe6c2c644623a4caff8',
    messagingSenderId: '919591073641',
    projectId: 'healthvault-6af37',
    storageBucket: 'healthvault-6af37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0LT5z0CcUZz17ZQZ59JprJCyCvvFIM0',
    appId: '1:919591073641:ios:0d46036e93fa41df4caff8',
    messagingSenderId: '919591073641',
    projectId: 'healthvault-6af37',
    storageBucket: 'healthvault-6af37.appspot.com',
    iosClientId: '919591073641-dueuu1uortre6geqviac9a31j2ukgian.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0LT5z0CcUZz17ZQZ59JprJCyCvvFIM0',
    appId: '1:919591073641:ios:0d46036e93fa41df4caff8',
    messagingSenderId: '919591073641',
    projectId: 'healthvault-6af37',
    storageBucket: 'healthvault-6af37.appspot.com',
    iosClientId: '919591073641-dueuu1uortre6geqviac9a31j2ukgian.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthVault',
  );
}
